### ISSUE TITLE
Unsupported flag DT_FLAG_1

### ISSUE THREAD

**Issue by RossComputerGuy** [termux/termux-elf-cleaner#13]
I used `termux-elf-cleaner` on a program and I still get these messages.

![Screenshot from 2020-05-06 14-07-25](https://user-images.githubusercontent.com/19699320/81228560-1f8d0c00-8fa3-11ea-8a91-e7a6b36e479b.png)

**Comment by Grimler91** [comment]
What is your output of `termux-info`?

**Comment by RossComputerGuy** [comment]
![Screenshot from 2020-05-06 21-13-02](https://user-images.githubusercontent.com/19699320/81253847-68ae8180-8fde-11ea-98a6-0a3fa95cc68e.png)

**Comment by xeffyr** [comment]
This program is executed from make file. Are you sure that it is not being rebuilt after `termux-elf-cleaner` ? How does it behave after `termux-elf-cleaner` and **manual** execution ?

**Comment by xeffyr** [comment]
Consider patching makefile by adding `termux-elf-cleaner doc/chew` before `doc/chew` is being executed.

**Comment by RossComputerGuy** [comment]
I know the file is not rebuilt because I looked at the makefile and the binary is a Target so it will compile if it does not exist.

**Comment by xeffyr** [comment]
> so it will compile if it does not exist.

Yes, but you are forgetting about timestamps. See in https://github.com/termux/termux-packages/blob/master/packages/mutt/build.sh#L40 how we workaround that problem.

**Comment by xeffyr** [comment]
Does **manual** execution after termux-elf-cleaner show the same warnings ?

**Comment by RossComputerGuy** [comment]
No, it only happens on a clean build.

**Comment by xeffyr** [comment]
Then way to fix is at https://github.com/termux/termux-elf-cleaner/issues/13#issuecomment-625272411.

**Comment by RossComputerGuy** [comment]
I manualy compile chew. https://github.com/ExpidusOS/sdk/blob/redesign/toolchain/source/binutils/pkg.mk#L8

**Comment by xeffyr** [comment]
But you are not fixing its timestamp and make will rebuild it.

**Comment by RossComputerGuy** [comment]
It doesn't recompile because if it did then I would've gotten an error saying `x86_64` is not a file.

**Comment by xeffyr** [comment]
Ok, can you gzip & attach that file here ?

**Comment by xeffyr** [comment]
After binutils build.

**Comment by RossComputerGuy** [comment]
The chew file?

**Comment by xeffyr** [comment]
Yes.

**Comment by RossComputerGuy** [comment]
[chew.gz](https://github.com/termux/termux-elf-cleaner/files/4594085/chew.gz)

**Comment by xeffyr** [comment]
You didn't run termux-elf-cleaner or it is really got rebuild.

Original file:
```
/tmp/test03 $ readelf -d chew.orig

Dynamic section at offset 0x5cf0 contains 30 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x000000000000001d (RUNPATH)            Library runpath: [/data/data/com.termux/files/usr/lib]
 0x0000000000000020 (PREINIT_ARRAY)      0x6cc0
 0x0000000000000021 (PREINIT_ARRAYSZ)    0x10
 0x0000000000000019 (INIT_ARRAY)         0x6cd0
 0x000000000000001b (INIT_ARRAYSZ)       16 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x6ce0
 0x000000000000001c (FINI_ARRAYSZ)       16 (bytes)
 0x0000000000000004 (HASH)               0x358
 0x000000006ffffef5 (GNU_HASH)           0x408
 0x0000000000000005 (STRTAB)             0x668
 0x0000000000000006 (SYMTAB)             0x428
 0x000000000000000a (STRSZ)              231 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000003 (PLTGOT)             0x6f10
 0x0000000000000002 (PLTRELSZ)           480 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x878
 0x0000000000000007 (RELA)               0x7a0
 0x0000000000000008 (RELASZ)             216 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW PIE
 0x000000006ffffffe (VERNEED)            0x780
 0x000000006fffffff (VERNEEDNUM)         1
 0x000000006ffffff0 (VERSYM)             0x750
 0x000000006ffffff9 (RELACOUNT)          6
 0x0000000000000000 (NULL)               0x0
```

With `termux-elf-cleaner`:
```
/tmp/test03 $ ./termux-elf-cleaner chew
termux-elf-cleaner: Replacing unsupported DF_1_* flags 134217729 with 1 in 'chew'
/tmp/test03 $ readelf -d chew

Dynamic section at offset 0x5cf0 contains 30 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x000000000000001d (RUNPATH)            Library runpath: [/data/data/com.termux/files/usr/lib]
 0x0000000000000020 (PREINIT_ARRAY)      0x6cc0
 0x0000000000000021 (PREINIT_ARRAYSZ)    0x10
 0x0000000000000019 (INIT_ARRAY)         0x6cd0
 0x000000000000001b (INIT_ARRAYSZ)       16 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x6ce0
 0x000000000000001c (FINI_ARRAYSZ)       16 (bytes)
 0x0000000000000004 (HASH)               0x358
 0x000000006ffffef5 (GNU_HASH)           0x408
 0x0000000000000005 (STRTAB)             0x668
 0x0000000000000006 (SYMTAB)             0x428
 0x000000000000000a (STRSZ)              231 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000003 (PLTGOT)             0x6f10
 0x0000000000000002 (PLTRELSZ)           480 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x878
 0x0000000000000007 (RELA)               0x7a0
 0x0000000000000008 (RELASZ)             216 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffffe (VERNEED)            0x780
 0x000000006fffffff (VERNEEDNUM)         1
 0x000000006ffffff0 (VERSYM)             0x750
 0x000000006ffffff9 (RELACOUNT)          6
 0x0000000000000000 (NULL)               0x0
/tmp/test03 $
```

**Comment by xeffyr** [comment]
Notice the change in `0x000000006ffffffb (FLAGS_1)`.

**Comment by xeffyr** [comment]
Issue is not with termux-elf-cleaner.

**Comment by RossComputerGuy** [comment]
It wouldn't rebuild the file because if it did then I'd get an error saying that `x86_64` is not a file. And the file is a target in binutils's Makefiles. And what about fixing it so `DT_FLAG_1` doesn't show up as a warning? Only `DT_1_*` are removed.

**Comment by xeffyr** [comment]
`make` verifies both whether target is build and whether timestamp is up-to-date. That how it works. You making target outside of make session and further make session will **ignore that target**.

`DT_1_*` is just incosistency of messages. DF_1, DT_1. DT_FLAGS_1 all they mean same thing: https://github.com/termux/termux-elf-cleaner/blob/master/termux-elf-cleaner.cpp#L100

**Comment by RossComputerGuy** [comment]
So that means by compiling outside, it shouldn't recompile the file but your saying it's been recompiled even though it would've errored from `x86_64` not being a file?

**Comment by xeffyr** [comment]
It shouldn't recompile once you set target's timestamp in future, i.e. `time -d 'next hour' ...`.

**Comment by xeffyr** [comment]
Tested the original & cleaned binary in my Anbox installation:
```
x86_64:/data/local/tmp $ ./chew.orig                                                                                                                                                                      
WARNING: linker: /data/local/tmp/chew.orig: unsupported flags DT_FLAGS_1=0x8000001
^C
130|x86_64:/data/local/tmp $ ./chew                                                                                                                                                                       
^C
130|x86_64:/data/local/tmp $
```
So the `termux-elf-cleaner` does its work as I wrote before.
