### ISSUE TITLE
Cant install (OPEN SSL error)

### ISSUE THREAD

**Issue by emahuni** [termux/termux-elf-cleaner#9]
pkg install termux-elf-cleaner
Hit:1 https://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
17 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  termux-elf-cleaner
0 upgraded, 1 newly installed, 0 to remove and 17 not upgraded.
Need to get 7968 B of archives.
After this operation, 45.1 kB of additional disk space will be used.
Err:1 https://termux.net stable/main arm termux-elf-cleaner arm 1.2
  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to termux.net:443
E: Failed to fetch https://termux.net/dists/stable/main/binary-arm/termux-elf-cleaner_1.2_arm.deb  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to termux.net:443
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by emahuni** [comment]
Ohhh ok. I can do it like that by the way? :D, super, it downloaded, ok let me install that thanks.

**Comment by nithesh-ai** [comment]
When I was trying to install metasploit in termux it showing error like could not load openssl how can I resolve it
